include_recipe 'infrastructure::xterm'
include_recipe 'infrastructure::bash_profile'
include_recipe 'infrastructure::httpd'
include_recipe 'infrastructure::varLog'
include_recipe 'infrastructure::cfn'
include_recipe 'infrastructure::application'
